### ISSUE TITLE
Question about web interfaces

### ISSUE THREAD

**Issue by grib0** [YggdrasiI/PBStats#1]
Hi,

I setup a pitboss game with 2 friends. Each time we complete a turn we need to send an email or whatsapp message but sometime we missed the message or forgot. We would like a web page to see who has his turn to play. 
Your project sounds great although I don't understand everything. 

I don't want to loose or crash our actual game. I would like to know if the actual web interface in python or the old one in php can work without having to install the complete mod and restart our game ?

Thank you for the answer.

Regards

**Comment by YggdrasiI** [comment]
Hello grib0,

the interaction between webinterface and game will be done by a mod component which will be loaded at startup of the Pitboss server. Thus, it is not possible to use the webinterface without installing the mod (or integrating it into the currently used mod).

The PB Mod uses the same save game format as Civ4:BTS. If you play a normal BTS game it would be possible to convert your actual game into one with mod and you do not loose it. 
With access to a Linux system you could use PBStats/PBs/convertSavesToMod.sh to add/change the mod name in the save game (without password). Moreover, you had to rename PB Mod_v6/Assets/CvGameCoreDLL.dll.18players into CvGameCoreDLL.dll and then continue with the installation steps, described in README.md.

Regards

P.S Unfortunately, the setup of the server is not so easy as whished… 
There are several reasons why I did not improve the code/setup, but I offer you to made these steps if you send me an mail with the current save to funwithkinect@googlemail.com

**Comment by Zulan** [comment]
For the website part, feel free to make use of http://civ.zulan.net/pbspy/, no need to host that yourself.

**Comment by grib0** [comment]
Thank you for your answers. I will try to integrate the mod during the next weeks, I found that the download of the game is very long and that you fixed it. Wich version you I take ? The master branch or the v6 one ?

**Comment by YggdrasiI** [comment]
> Wich version you I take ? The master branch or the v6 one?

I suggest the master branch (equals PB_Mod_v7).

>  I found that the download of the game is very long and that you fixed it.

Yes, that fix could save a lot of life time ;)
Please note that we didn't remove the hardwired 10kb/s handbrake in the executable, but translate the reading of the file into an handy http request of the file. As side effect this made the download more reliable.
